### ISSUE TITLE
Auto Login is causing a server error 500

### ISSUE THREAD

**Issue by jbyron** [Primeaxiom/StellarRealms#1]
When logging in to stellarrealms using http://www.stellarrealms.com many users are getting an error 500 back.

Upon further investigation this seems to be happening only when the user has "automatically login" checked on the login screen.

**Comment by Vorkuta26** [comment]
Autologin now shows "Autologin" text on default.asp or showing a token string instead.

**Comment by jbyron** [comment]
Want to try again pls?  I made a tweak.  I haven't been able to reproduce it on my side at all so I can't confirm if it's still happening or not.

**Comment by TheZaphodBeeblebrox** [comment]
This appears to be working on my front. My cousin was having trouble with her login screen but I'll get back to you on that.  My phone isn't recognizing the auto login feature, but my computer is.  No biggie, but I'm now regretting my tremendously long name. Haha.

**Comment by TheZaphodBeeblebrox** [comment]
Okay, going to stellarrealms.com takes my cousin to Default.  After signing in, she is linked to the Login page and gets an error page:

Err: (-2147220960) The "SendUsing" configuration value is invalid. 
SrvErr: () 
Src: 
Location: File: /login.asp - Line: 136 - Pos: -1
Client IP: 71.238.235.72
Referrer: http://www.stellar-realms.com/default.asp

Clicking return to stellar-realms takes her back to the opening.

However, if she clicks auto login, then she gets the error page again.  However, when she clicks the return to stellar-realms link on the error page, it correctly takes her to the main page.

I should reiterate, this does not happen on my computer.  She uses Chrome but has windows vista and I'm still operating on an old and busted windows xp.  So I'm extremely baffled.

**Comment by TheZaphodBeeblebrox** [comment]
Autologin no longer functions.  It resets upon loging out or opening a new page.  - I am sure this is on purpose as I presume you've disabled it.

My cousin's planet still had problems going in, and today she couldn't get in at all because the autologin was disabled.  But, typing main.asp after logging in allowed her to access her planet.

However, I had an idea.  I tried logging into my planet on her computer and it worked! There was no bug to duplicate.  Only repeatable upon logging into her planet.  So, I told her to delete her planet, and recreate it again.  Problem solved, no need to bypass the error page.

However, she did record the error page's identity and this is the info it showed:

LoginSessionID: 15b5771092df42beaacccf9f5635c709
authUserId: 1574
authPlanetId: -1

The planet id registering as negative must've had something to do with it.  Perhaps a new code was not recognizing old code.  In either case, the error has been fixed on the player's end.

WIth the exception of autologin not being active or tested - this case is solved?
